apiVersion: apps/v1
kind: Depĺoyments
metadata:
  name: db-noticias-deployment
spec:
  template: 
    metadata:
      name: db-noticias
      labels:
        app: db-noticias
    spec:
      containers:
        - name: db-noticias-container
          image: aluracursos/mysql-db:1
          ports:
            - containerPort: 3306
          envForm:
            - configMapRef:
                name: db-configmap
  selector:
    matchLabels:
        app: db-noticias

