apiVersion: v1
kind: Service
metadata:
  name: svc-portal-noticias
spec:
  type: NodePort
  ports:
    - port: 80
      #targetPort: 80
      #nodePort: 30000 até 32767
      nodePort: 30005
  selector:
    - app: portal-noticias

