apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
spec: 
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: pv-disk   # nome do disco criando dentro do ambiente do google plataform
  storageClassName: standard

  #google cloud