apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  fstype: ext4


  #https://kubernetes.io/docs/concepts/storage/storage-classes/#gce-pd


  # kubectl get sc